**<h1>Huawei HCCDA-AI</h1> Batach II**<hr>
**LAB 1** <br>
**Date: 13-sep-2026**

In [1]:
print('welcome sir')

welcome sir


**Variable:** Variable is just like a container in which we store a value.<br>
'#' we use hashtag for comment ... or we write the purpose of particular line ....
note: After the # the written message is not execute it is the not part of code. It is just a informaion.

In [34]:
a = "ALI" # Here we store a value ALI in variable a

In [33]:
a # to dislay which value is store in a ...

'ALI'

**print()** is use for display message on screen

In [35]:
print(a)

ALI


**Datatype:** In python language we don't declare datatype.
<br>
below we check he datatypes of differnet variable
<br>
**type()** This is a function which showw the datatype of variable

In [36]:
B = "Ahmad"
print(type(B)) # string

<class 'str'>


In [40]:
x = 'A'
print(type(x)) # string

<class 'str'>


In [37]:
C = 2345
print(type(C)) # integer

<class 'int'>


In [38]:
D = 3.7
print(type(D)) # float

<class 'float'>


Just like a **structure** in c or c++ ( **Struct** : we can store the differnet datatype of variable) same like this in python we use the **List, tupple, Dictionary**


##**LIST**<hr>
List is a mutable datatye we can change any value in list. <br> list is a most commonly use data structure <br>
list is use square brackets

In [42]:
list_1 = [1, 2, 4.5, "ALI"]
print(list_1)

[1, 2, 4.5, 'ALI']


In [46]:
print(type(list_1)) # Check Datatype

<class 'list'>


**slicing** <br>
 Below we will find any value by index no . In python index no is start from '0'

In [48]:
list_1[2]

4.5

Now we will change the value in list by using index no

In [51]:
list_1[2]=9     # we replace the value 3.4
print(list_1)

[1, 2, 9, 'ALI']


In [53]:
list_1[1]="Ahmad"
list_1[2]=76
list_1[3]=3.9
print(list_1)

[1, 'Ahmad', 76, 3.9]


##**TUPLE** <br>
tupple is a immutable <br>
can't cahnge any Element in tupple <br>
tuple use small brackets

In [66]:
# Make a standard tupple
fruits = ("apple", "banana", "cherry")
print("Original Tuple:", fruits)


Original Tuple: ('apple', 'banana', 'cherry')


In [70]:
fruits = ("apple", "banana", "cherry")
# Mistake: try to change index 1 (banana) to "mango"
# rememmber it will no change because tupple is immutable data
fruits[1] = "mango"

# ❌ Error: TypeError: 'tuple' object does not support item assignment
# The error shows in line no 4

TypeError: 'tuple' object does not support item assignment

What We CAN Do with a Tuple **(Allowed Operations)**
we cannot change elements, but you can read ** (access) ** them and use **slicing** just like a list:


In [71]:

numbers = (10, 20, 30, 40, 50)

# A. Accessing a specific element
print(numbers[2])   # Prints 30 (the element at index 2)

# B. Slicing (Extracting a part of the tuple)
print(numbers[1:4]) # Prints (20, 30, 40) (index 4 is excluded)

# C. Checking total length
print(len(numbers)) # Prints 5 (total number of elements)


30
(20, 30, 40)
5


**Special Tip:** Single Element Tuple <br>
If you want to create a tuple with only ONE element, you MUST add a trailing comma `,`. <br>
Otherwise, Python will treat it as a regular string or integer.


In [74]:
wrong_tuple = ("apple")  # This creates a standard String, NOT a tuple
right_tuple = ("apple",) # Adding the comma makes it a valid Tuple

# Display
print(wrong_tuple)
print(right_tuple)

apple
('apple',)


In [75]:
# Display their types
print(type(wrong_tuple)) # This will show string datatype
print(type(right_tuple)) # This will show tuple datatype

<class 'str'>
<class 'tuple'>


# Dictionaries

*   **Definition:** A Python Dictionary (dict) stores data in **key: value pairs** inside curly brackets {}.
*   **No Index Numbers:** Unlike lists, you do not look up items using numbers like 0 or 1. Instead, you use a unique **Key** to access its **Value**.
*   Dictionaries are **mutable**.
*  Keys must be unique (no duplicates allowed).


In [83]:
student = {
    "name": "Ahmad",
    "age": 22,
    "course": "Python",
    "grade": "A"
}

print(student)


{'name': 'Ahmad', 'age': 22, 'course': 'Python', 'grade': 'A'}


In [82]:
# 2. ACCESSING VALUES
print(student["name"])      # Print only students name
print(student["course"])     # Print only course


Ahmad
Python


In [84]:
# Adding a  new key-value pair
student["city"] = "Lahore"  # Adds "city": "Lahore" to the dictionary
print(student)

{'name': 'Ahmad', 'age': 22, 'course': 'Python', 'grade': 'A', 'city': 'Lahore'}


In [85]:
student["Remarks"] = "Good"
print(student)

{'name': 'Ahmad', 'age': 22, 'course': 'Python', 'grade': 'A', 'city': 'Lahore', 'Remarks': 'Good'}


**NUMPY**  
<br>
*   **NumPy** stands for Numerical Python. It is a powerful library used for working with numerical data in the form of arrays.
*  **array** is a collection of elements of the same data type.
*   **Dimensions:**
    *   **1D Array (1-Dimensional):** A single row of elements (like a vector).
    *   **2D Array (2-Dimensional):** Elements arranged in rows and columns (like a matrix or table).


In [87]:
import numpy as np

# 1D ARRAY (Single row)
Dimension_1 = np.array([1, 2, 5])

# 2. 2D ARRAY (Rows and Columns)
# Note: It contains a list of lists inside square brackets [[...], [...]]
Dimension_2 = np.array([[1, 5, 7], [3, 95, 6]])


In [90]:
print(Dimension_1) # Display 1 D array

print(Dimension_2) # Display 2 D array

[1 2 5]
[[ 1  5  7]
 [ 3 95  6]]
