In [2]:
# Before import this library, make sure you have installed it using pip install numpy in your terminal or command prompt.
import numpy as np 

Without any confuision you can learn easily . just do practice ... <br>
let's start in one trick .... trick is hidden <br> Trick easy ha thora mind lgayna pary ga

# Numpy 2D Array
**2D array in numpy is a matrix, and it has rows and columns, so we can access the elements of the matrix by using the index of the row and column, and the index start from 0, so d2[0,0] means row 0 and column 0, which is 1**

In [8]:
d2 = np.array([
    [1,2],
    [10,20], 
    [1,3],
    [100,200],
    [1000,2000]
    ])

print("2D array: \n",d2)
print("\n Number of dimensions:",d2.ndim)  
print("\n Shape of array:",d2.shape)
print("\n Number of rows:",d2.shape[0]) 
print("\n Number of columns:",d2.shape[1])
# how many elements are there in the array (row * col)
print("\n size of array:",d2.size)

2D array: 
 [[   1    2]
 [  10   20]
 [   1    3]
 [ 100  200]
 [1000 2000]]

 Number of dimensions: 2

 Shape of array: (5, 2)

 Number of rows: 5

 Number of columns: 2

 size of array: 10


# Slicing

In [4]:
# Slicing is a technique to extract a portion of an array. In 2D arrays, slicing can be done using the following syntax: array[row,column]
# make a 2d array of 5 rows and 2 columns and slice it to get the first 3 rows and the first column.
d2 = np.array([
    [1,2],
    [10,20], 
    [1,3],
    [100,200],
    [1000,2000]
    ])

print("2D array: \n",d2)
print("\n Sliced 2D array: \n",d2[:3, :1])

2D array: 
 [[   1    2]
 [  10   20]
 [   1    3]
 [ 100  200]
 [1000 2000]]

 Sliced 2D array: 
 [[ 1]
 [10]
 [ 1]]


In [5]:
d2 = np.array([
    [1,2],
    [10,20], 
    [1,3],
    [100,200],
    [1000,2000]
    ])

print("2D array: \n",d2)
print("\n Number of dimensions:",d2.ndim)  
print("\n Shape of array:",d2.shape)
print("\n Number of rows:",d2.shape[0]) 
print("\n Number of columns:",d2.shape[1])

2D array: 
 [[   1    2]
 [  10   20]
 [   1    3]
 [ 100  200]
 [1000 2000]]

 Number of dimensions: 2

 Shape of array: (5, 2)

 Number of rows: 5

 Number of columns: 2


In [6]:
# 2D array
d2 = np.array([
    [1,2],
    [10,20], 
    [1,3],
    [100,200],
    [1000,2000]
    ]) # 2D array
# here we have just [row,column] and the index start from 0, so d2[0,0] means row 0 and column 0, which is 1
print("it will show us element at index [0,0]:",d2[0,0]) 
# here we have just [row,column] and the index start from 0, so d2[0,1] means row 0 and column 1, which is 2
print("it will show us element at index [0,1]:",d2[0,1])
# here we have just [row,column] and the index start from 0, so d2[1,0] means row 1 and column 0, which is 10
print("it will show us element at index [1,0]:",d2[1,0])
# here we have just [row,column] and the index start from 0, so d2[1,1] means row 1 and column 1, which is 20
print("it will show us element at index [1,1]:",d2[1,1])
# here we have just [row,column] and the index start from 0, so d2[2,0] means row 2 and column 0, which is 1
print("it will show us element at index [2,0]:",d2[2,0])
# here we have just [row,column] and the index start from 0, so d2[2,1] means row 2 and column 1, which is 3
print("it will show us element at index [2,1]:",d2[2,1])
# here we have just [row,column] and the index start from 0, so d2[3,0] means row 3 and column 0, which is 100
print("it will show us element at index [3,0]:",d2[3,0])
# here we have just [row,column] and the index start from 0, so d2[3,1] means row 3 and column 1, which is 200
print("it will show us element at index [3,1]:",d2[3,1])
# here we have just [row,column] and the index start from 0, so d2[4,0] means row 4 and column 0, which is 1000
print("it will show us element at index [4,0]:",d2[4,0])
# here we have just [row,column] and the index start from 0, so d2[4,1] means row 4 and column 1, which is 2000
print("it will show us element at index [4,1]:",d2[4,1])

it will show us element at index [0,0]: 1
it will show us element at index [0,1]: 2
it will show us element at index [1,0]: 10
it will show us element at index [1,1]: 20
it will show us element at index [2,0]: 1
it will show us element at index [2,1]: 3
it will show us element at index [3,0]: 100
it will show us element at index [3,1]: 200
it will show us element at index [4,0]: 1000
it will show us element at index [4,1]: 2000
