In [14]:
# Before import this library, make sure you have installed it using pip install numpy in your terminal or command prompt.
import numpy as np 

Without any confuision you can learn easily . just do practice ... <br>
let's start in one trick .... trick is hidden <br> Trick easy ha thora mind lgayna pary ga

In [15]:
d3= np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
print(" 3D array:\n",d3) # 3D array
print("\n Number of dimensions:",d3.ndim)
print("\n Shape of array:",d3.shape)
print("\n Number of rows:",d3.shape[0])
print("\n Number of columns:",d3.shape[1])
print("\n Number of layers:",d3.shape[2])
print("\n size of array:",d3.size) # how many elements are there in the array (layer * rw * col)

 3D array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

 Number of dimensions: 3

 Shape of array: (3, 2, 2)

 Number of rows: 3

 Number of columns: 2

 Number of layers: 2

 size of array: 12


# slicing

In [16]:
# 3D array
d3= np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
print(" 3D array:\n",d3) # 3D array
print("\nit will show us element at index [0,0,0]:",d3[0,0,0])
print("it will show us element at index [0,0,1]:",d3[0,0,1]) 
print("it will show us element at index [0,1,0]:",d3[0,1,0])
print("it will show us element at index [0,1,1]:",d3[0,1,1])
print("it will show us element at index [1,0,0]:",d3[1,0,0]) 
print("it will show us element at index [1,0,1]:",d3[1,0,1]) 
print("it will show us element at index [1,1,0]:",d3[1,1,0]) 
print("it will show us element at index [1,1,1]:",d3[1,1,1])
print("it will show us element at index [2,0,0]:",d3[2,0,0]) 
print("it will show us element at index [2,0,1]:",d3[2,0,1]) 
print("it will show us element at index [2,1,0]:",d3[2,1,0]) 
print("it will show us element at index [2,1,1]:",d3[2,1,1]) 


 3D array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

it will show us element at index [0,0,0]: 1
it will show us element at index [0,0,1]: 2
it will show us element at index [0,1,0]: 3
it will show us element at index [0,1,1]: 4
it will show us element at index [1,0,0]: 5
it will show us element at index [1,0,1]: 6
it will show us element at index [1,1,0]: 7
it will show us element at index [1,1,1]: 8
it will show us element at index [2,0,0]: 9
it will show us element at index [2,0,1]: 10
it will show us element at index [2,1,0]: 11
it will show us element at index [2,1,1]: 12


In [17]:
D3 = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[5, 6], [7, 8], [9, 10]],
    [[9, 10], [11, 12], [13, 14]]
])

print("3D array:\n", D3)

print("\nit will show us element at index [0,0,0]:", D3[0,0,0])
print("it will show us element at index [0,0,1]:", D3[0,0,1])
print("it will show us element at index [0,1,0]:", D3[0,1,0])
print("it will show us element at index [0,1,1]:", D3[0,1,1])
print("it will show us element at index [0,2,0]:", D3[0,2,0])
print("it will show us element at index [0,2,1]:", D3[0,2,1])
print("it will show us element at index [1,0,0]:", D3[1,0,0])
print("it will show us element at index [1,0,1]:", D3[1,0,1])
print("it will show us element at index [1,1,0]:", D3[1,1,0])
print("it will show us element at index [1,1,1]:", D3[1,1,1])
print("it will show us element at index [1,2,0]:", D3[1,2,0])
print("it will show us element at index [1,2,1]:", D3[1,2,1])
print("it will show us element at index [2,0,0]:", D3[2,0,0])
print("it will show us element at index [2,0,1]:", D3[2,0,1])
print("it will show us element at index [2,1,0]:", D3[2,1,0])
print("it will show us element at index [2,1,1]:", D3[2,1,1])
print("it will show us element at index [2,2,0]:", D3[2,2,0])
print("it will show us element at index [2,2,1]:", D3[2,2,1])

3D array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]

 [[ 9 10]
  [11 12]
  [13 14]]]

it will show us element at index [0,0,0]: 1
it will show us element at index [0,0,1]: 2
it will show us element at index [0,1,0]: 3
it will show us element at index [0,1,1]: 4
it will show us element at index [0,2,0]: 5
it will show us element at index [0,2,1]: 6
it will show us element at index [1,0,0]: 5
it will show us element at index [1,0,1]: 6
it will show us element at index [1,1,0]: 7
it will show us element at index [1,1,1]: 8
it will show us element at index [1,2,0]: 9
it will show us element at index [1,2,1]: 10
it will show us element at index [2,0,0]: 9
it will show us element at index [2,0,1]: 10
it will show us element at index [2,1,0]: 11
it will show us element at index [2,1,1]: 12
it will show us element at index [2,2,0]: 13
it will show us element at index [2,2,1]: 14
